### ISSUE TITLE
Error while running run_amn_featreg

### ISSUE THREAD

**Issue by ghost** [eparisotto/ActorMimic#1]
I am able to run the policy reg script without any errors but the featreg gives an error "Invalid option useRGB=true" even though the same option is there in env_params in run_amn_polreg. Would like to know the fix.

**Comment by eparisotto** [comment]
Sorry for the late response but which file were you running specifically? I have tried all the files in the scripts/ folder and they were working on my computer.

**Comment by eparisotto** [comment]
Closing this issue, I think the problem was from an earlier commit.
